# Generated by Django 4.2.1 on 2023-09-21 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0008_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='header_iamge',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
