# Generated by Django 4.2.1 on 2023-09-21 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0009_post_header_iamge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='header_iamge',
            new_name='header_image',
        ),
    ]
