# Generated by Django 4.2.5 on 2023-09-24 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0012_profile_facebook_url_profile_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('SOLD', 'SOLD')], default='PENDING', max_length=20),
        ),
    ]
