# Generated by Django 4.2.1 on 2023-09-26 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0018_alter_message_receiver_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='has_new_messages',
            field=models.BooleanField(default=False),
        ),
    ]
